plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {
		name = 'Modrinth'
		url = 'https://api.modrinth.com/maven'
		content {
			includeGroup 'maven.modrinth'
		}
	}
	maven {
		name = 'TerraformersMC'
		url = 'https://maven.terraformersmc.com/releases'
	}
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"rigtune" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

fabricApi {
	configureTests {
		createSourceSet = true
		modId = "rigtune-gametest"
		enableGameTests = false
		enableClientGameTests = true
		eula = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	compileOnly "com.terraformersmc:modmenu:${project.modmenu_version}"
	localRuntime "com.terraformersmc:modmenu:${project.modmenu_version}"
	localRuntime "maven.modrinth:sodium:${project.sodium_version}"

	testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
}

sourceSets {
	test {
		compileClasspath += sourceSets.client.compileClasspath + sourceSets.client.output
		runtimeClasspath += sourceSets.client.runtimeClasspath + sourceSets.client.output
	}
}

test {
	useJUnitPlatform()
	workingDir = layout.buildDirectory.dir("junit-run").get().asFile
	doFirst { workingDir.mkdirs() }
}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
	it.options.encoding = 'UTF-8'
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName" }
	}
}
